# Generated by Django 4.1 on 2022-08-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
