# Generated by Django 4.1 on 2022-09-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_imageabout_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.CharField(max_length=200),
        ),
    ]
